name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t juice-shop .

      # Gitleaks (ne bloque pas pipeline)
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      # Semgrep
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Trivy filesystem scan
      - name: Trivy FS
        run: trivy fs .
        continue-on-error: true

      # Trivy image scan
      - name: Trivy Image
        run: trivy image juice-shop
        continue-on-error: true

      # Run container
      - name: Run container
        run: docker run -d -p 3000:3000 --name juice juice-shop

      # Wait app startup
      - name: Wait for app
        run: sleep 20

      # ZAP Scan
      - name: ZAP Scan
        run: |
          docker run --network host ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t http://localhost:3000
        continue-on-error: true.
