name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t juice-shop .

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy FS
        run: trivy fs .
        continue-on-error: true

      - name: Trivy Image
        run: trivy image juice-shop
        continue-on-error: true

      - name: Run container
        run: docker run -d -p 3000:3000 --name juice juice-shop

      - name: Wait for app
        run: sleep 20

      - name: ZAP Scan
        run: |
          docker run --network host ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3000
        continue-on-error: true